# Generated by Django 5.2.6 on 2025-10-12 23:28

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exchange_agreement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgencyAdminProxy",
            fields=[],
            options={
                "verbose_name": "Agency",
                "verbose_name_plural": "Agencies",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("exchange_agreement.agency",),
        ),
        migrations.CreateModel(
            name="AuthorityAdminProxy",
            fields=[],
            options={
                "verbose_name": "Authority",
                "verbose_name_plural": "Authorities",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("exchange_agreement.authority",),
        ),
        migrations.CreateModel(
            name="CompanyAdminProxy",
            fields=[],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("exchange_agreement.company",),
        ),
    ]
