# Generated by Django 5.2.6 on 2025-10-03 18:13

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_contratto", models.CharField(max_length=64, unique=True)),
                ("data_inizio", models.DateField()),
                ("data_fine", models.DateField(blank=True, null=True)),
                (
                    "gara_id",
                    models.CharField(
                        blank=True,
                        help_text="Identificativo della gara associata",
                        max_length=64,
                    ),
                ),
                (
                    "tipo_contratto",
                    models.CharField(
                        choices=[("avvio", "Avvio"), ("rinnovo", "Rinnovo")],
                        max_length=7,
                    ),
                ),
                (
                    "versione",
                    models.PositiveIntegerField(
                        help_text="Numero di versione progressivo per la coppia committente/appaltante"
                    ),
                ),
                (
                    "programma_da_contratto_stato",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se è presente un servizio di programma",
                    ),
                ),
                (
                    "programma_da_contratto_file",
                    models.FileField(
                        blank=True,
                        help_text="File XML del programma associato",
                        null=True,
                        upload_to="contratti/programmi/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contratto",
                "verbose_name_plural": "Contratti",
            },
        ),
        migrations.CreateModel(
            name="Ente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("descrizione", models.TextField(blank=True)),
                (
                    "estensione_geografica",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True,
                        help_text="Estensione geografica dell'ente in formato WGS84",
                        null=True,
                        srid=4326,
                    ),
                ),
                (
                    "tipo_ente",
                    models.CharField(
                        choices=[
                            ("regione", "Regione"),
                            ("comune", "Comune"),
                            ("agenzia", "Agenzia"),
                            ("azienda", "Azienda"),
                            ("altro", "Altro"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ente",
                "verbose_name_plural": "Enti",
            },
        ),
        migrations.CreateModel(
            name="Lotto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descrizione", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Lotto",
                "verbose_name_plural": "Lotti",
            },
        ),
        migrations.CreateModel(
            name="ContractDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("file", models.FileField(upload_to="contratti/documenti/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documenti",
                        to="exchange_agreement.contract",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento del contratto",
                "verbose_name_plural": "Documenti del contratto",
            },
        ),
        migrations.AddField(
            model_name="contract",
            name="appaltante",
            field=models.ForeignKey(
                help_text="Ente appaltante (azienda)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contratti_appaltante",
                to="exchange_agreement.ente",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="committente",
            field=models.ForeignKey(
                help_text="Ente committente (agenzia)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contratti_committente",
                to="exchange_agreement.ente",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="lotto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contratti",
                to="exchange_agreement.lotto",
            ),
        ),
        migrations.CreateModel(
            name="ContractIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codice", models.CharField(max_length=64)),
                ("descrizione", models.CharField(blank=True, max_length=255)),
                ("valore", models.CharField(blank=True, max_length=255)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicatori",
                        to="exchange_agreement.contract",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicatore del contratto",
                "verbose_name_plural": "Indicatori del contratto",
                "unique_together": {("contract", "codice")},
            },
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.UniqueConstraint(
                fields=("committente", "appaltante", "versione"),
                name="unique_contract_version_per_pair",
            ),
        ),
    ]
