# Generated by Django 5.2.6 on 2025-10-12 22:17

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
import rpsd_config.exchange_agreement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Agency",
                "verbose_name_plural": "Agencies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="e.g. netex, siri_pt, siri_vm, ...", unique=True
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Dataset",
                "verbose_name_plural": "Datasets",
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="Lot",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Lot",
                "verbose_name_plural": "Lots",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Authority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "geographic_extent",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True,
                        help_text="Geographic extent in WGS84",
                        null=True,
                        srid=4326,
                    ),
                ),
                (
                    "authority_type",
                    models.CharField(
                        choices=[
                            ("region", "Region"),
                            ("municipality", "Municipality"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Authority",
                "verbose_name_plural": "Authorities",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "authority_type"),
                        name="uniq_authority_name_type",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("contract_code", models.CharField(max_length=64, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "tender_id",
                    models.CharField(
                        blank=True,
                        help_text="Associated tender/procurement identifier (optional; no dedicated table)",
                        max_length=64,
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[("start", "Start"), ("renewal", "Renewal")],
                        max_length=7,
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        help_text="Progressive serial for the pair (client_agency, contractor_company)"
                    ),
                ),
                (
                    "contract_program_file",
                    models.FileField(
                        blank=True,
                        help_text="NetEx file (XML/ZIP) with the contractual program",
                        null=True,
                        upload_to=rpsd_config.exchange_agreement.models.contract_program_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["xml", "zip"]
                            )
                        ],
                    ),
                ),
                (
                    "client_agency",
                    models.ForeignKey(
                        help_text="Client agency",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts_as_client",
                        to="exchange_agreement.agency",
                    ),
                ),
                (
                    "contractor_company",
                    models.ForeignKey(
                        help_text="Contractor company",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts_as_contractor",
                        to="exchange_agreement.company",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="exchange_agreement.lot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract",
                "verbose_name_plural": "Contracts",
                "ordering": ["-start_date", "contract_code"],
            },
        ),
        migrations.CreateModel(
            name="ContractDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "file",
                    models.FileField(
                        upload_to=rpsd_config.exchange_agreement.models.contract_doc_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "doc", "docx", "odt", "zip"]
                            )
                        ],
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="exchange_agreement.contract",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract document",
                "verbose_name_plural": "Contract documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Line",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique line identifier", max_length=64, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "authority",
                    models.OneToOneField(
                        help_text="Authority associated to the line (1:1)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="line",
                        to="exchange_agreement.authority",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        help_text="The line belongs to a lot (1:N)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="exchange_agreement.lot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Line",
                "verbose_name_plural": "Lines",
            },
        ),
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique stop identifier", max_length=64, unique=True
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="WGS84 coordinates (lon/lat)", srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name": "Stop",
                "verbose_name_plural": "Stops",
                "indexes": [
                    models.Index(fields=["code"], name="exchange_ag_code_acb235_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Structure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                (
                    "validation_schema",
                    models.FileField(
                        blank=True,
                        help_text="Validation schema for the section (XSD/XML/JSON/YAML)",
                        null=True,
                        upload_to=rpsd_config.exchange_agreement.models.structure_validation_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["xsd", "xml", "json", "yaml", "yml"]
                            )
                        ],
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="structures",
                        to="exchange_agreement.dataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Structure",
                "verbose_name_plural": "Structures",
                "ordering": ["dataset__slug", "name"],
            },
        ),
        migrations.CreateModel(
            name="IndicatorDef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("code", models.CharField(max_length=64, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("QUALITY", "Quality"),
                            ("QUANTITY", "Quantity"),
                            ("PUNCTUALITY", "Punctuality"),
                            ("OTHER", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(help_text="Indicator name", max_length=255)),
                ("description", models.TextField(blank=True)),
                ("formula", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "structure",
                    models.ForeignKey(
                        help_text="Which dataset structures/segments are required",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="indicators",
                        to="exchange_agreement.structure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicator definition",
                "verbose_name_plural": "Indicator definitions",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique trip identifier", max_length=64, unique=True
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.LineStringField(
                        blank=True,
                        help_text="Trip path (polyline in WGS84)",
                        null=True,
                        srid=4326,
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trips",
                        to="exchange_agreement.line",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip",
                "verbose_name_plural": "Trips",
            },
        ),
        migrations.CreateModel(
            name="TripStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(help_text="Stop order within the trip"),
                ),
                (
                    "stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="exchange_agreement.stop",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exchange_agreement.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip stop",
                "verbose_name_plural": "Trip stops",
                "ordering": ["trip__id", "sequence"],
            },
        ),
        migrations.AddField(
            model_name="trip",
            name="stops",
            field=models.ManyToManyField(
                related_name="trips",
                through="exchange_agreement.TripStop",
                to="exchange_agreement.stop",
            ),
        ),
        migrations.CreateModel(
            name="ContractIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "params",
                    models.JSONField(
                        blank=True,
                        help_text="Thresholds/weights/domain-specific configuration",
                        null=True,
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicators",
                        to="exchange_agreement.contract",
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="exchange_agreement.indicatordef",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract indicator",
                "verbose_name_plural": "Contract indicators",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("contract", "indicator"),
                        name="unique_contract_indicator",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="line",
            index=models.Index(fields=["lot"], name="exchange_ag_lot_id_8d03ed_idx"),
        ),
        migrations.AddIndex(
            model_name="line",
            index=models.Index(fields=["code"], name="exchange_ag_code_d061e6_idx"),
        ),
        migrations.AddConstraint(
            model_name="line",
            constraint=models.UniqueConstraint(
                fields=("authority",), name="unique_line_authority"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["client_agency", "contractor_company"],
                name="exchange_ag_client__92bcf2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["lot", "start_date"], name="exchange_ag_lot_id_916df1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.UniqueConstraint(
                fields=("client_agency", "contractor_company", "version"),
                name="unique_contract_version_per_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_date__gte", models.F("start_date")),
                    ("end_date__isnull", True),
                    _connector="OR",
                ),
                name="contract_date_range_ok",
            ),
        ),
        migrations.AddConstraint(
            model_name="structure",
            constraint=models.UniqueConstraint(
                fields=("dataset", "name"), name="unique_structure_dataset_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="tripstop",
            constraint=models.UniqueConstraint(
                fields=("trip", "stop"), name="unique_trip_stop"
            ),
        ),
        migrations.AddConstraint(
            model_name="tripstop",
            constraint=models.UniqueConstraint(
                fields=("trip", "sequence"), name="unique_trip_sequence"
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(fields=["line"], name="exchange_ag_line_id_404100_idx"),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(fields=["code"], name="exchange_ag_code_3e70c6_idx"),
        ),
    ]
