# SPDX-FileCopyrightText: 2025-2026 AGENZIA TPL BACINO CITTA' METROPOLITANA MILANO, MONZA E BRIANZA, LODI, PAVIA
# SPDX-License-Identifier: EUPL-1.2
# Generated by Django 5.2.6 on 2026-01-07 17:53

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchange_agreement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique route identifier", max_length=64, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Route",
                "verbose_name_plural": "Routes",
            },
        ),
        migrations.RemoveField(
            model_name="line",
            name="authority",
        ),
        migrations.RemoveField(
            model_name="line",
            name="lot",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="line",
        ),
        migrations.RemoveIndex(
            model_name="trip",
            name="exchange_ag_line_id_404100_idx",
        ),
        migrations.AddField(
            model_name="route",
            name="authority",
            field=models.ForeignKey(
                help_text="Authority associated to the route (1:N)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="routes",
                to="exchange_agreement.authority",
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="lot",
            field=models.ForeignKey(
                help_text="The route belongs to a lot (1:N)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="routes",
                to="exchange_agreement.lot",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trips",
                to="exchange_agreement.route",
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(fields=["route"], name="exchange_ag_route_i_4beb80_idx"),
        ),
        migrations.DeleteModel(
            name="Line",
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(fields=["lot"], name="exchange_ag_lot_id_de8d5d_idx"),
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(fields=["code"], name="exchange_ag_code_22c4a9_idx"),
        ),
        migrations.AddConstraint(
            model_name="route",
            constraint=models.UniqueConstraint(
                fields=("code", "lot"), name="unique_route_lot_identifier"
            ),
        ),
    ]
