# Generated by Django 5.2.6 on 2025-10-27 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_agreement", "0002_alter_line_authority"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="line",
            name="unique_line_authority",
        ),
        migrations.AlterField(
            model_name="line",
            name="authority",
            field=models.ForeignKey(
                help_text="Authority associated to the line (1:N)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lines",
                to="exchange_agreement.authority",
            ),
        ),
    ]
