# SPDX-FileCopyrightText: 2025-2026 AGENZIA TPL BACINO CITTA' METROPOLITANA MILANO, MONZA E BRIANZA, LODI, PAVIA
# SPDX-License-Identifier: EUPL-1.2
# Generated by Django 5.2.6 on 2026-01-07 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "exchange_agreement",
            "0002_route_remove_line_authority_remove_line_lot_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trips",
                to="exchange_agreement.route",
            ),
        ),
    ]
