# Generated by Django 5.2.6 on 2026-01-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_agreement", "0003_alter_trip_route"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indicatordef",
            name="structure",
        ),
        migrations.AddField(
            model_name="indicatordef",
            name="structures",
            field=models.ManyToManyField(
                help_text="Which dataset structures/segments are required",
                related_name="indicators",
                to="exchange_agreement.structure",
            ),
        ),
    ]
