# Generated by Django 5.2.6 on 2025-10-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_agreement", "0003_remove_line_unique_line_authority_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="line",
            constraint=models.UniqueConstraint(
                fields=("code", "lot"), name="unique_line_lot_identifier"
            ),
        ),
    ]
