# SPDX-FileCopyrightText: 2025-2026 AGENZIA TPL BACINO CITTA' METROPOLITANA MILANO, MONZA E BRIANZA, LODI, PAVIA
# SPDX-License-Identifier: EUPL-1.2
# Generated by Django 5.2.6 on 2026-02-14 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchange_agreement", "0004_remove_indicatordef_structure_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="closed_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="contract",
            name="replaced_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replaces",
                to="exchange_agreement.contract",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("closed", "Closed"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
    ]
