# Generated by Django 5.2.6 on 2026-02-14 09:31

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.operations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "exchange_agreement",
            "0005_contract_closed_at_contract_closed_reason_and_more",
        ),
    ]

    operations = [
        django.contrib.postgres.operations.BtreeGistExtension(),
        migrations.AddConstraint(
            model_name="contract",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    ("lot", "="),
                    (
                        models.Func(
                            models.F("start_date"),
                            models.F("end_date"),
                            function="daterange",
                            output_field=django.contrib.postgres.fields.ranges.DateRangeField(),
                            template="%(function)s(%(expressions)s, '[]')",
                        ),
                        "&&",
                    ),
                ],
                name="exclude_contract_overlap_per_lot",
            ),
        ),
    ]
