# Generated by Django 5.2.6 on 2026-02-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchange_agreement", "0006_contract_exclude_contract_overlap_per_lot"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contract",
            name="unique_contract_version_per_pair",
        ),
        migrations.AlterField(
            model_name="contract",
            name="version",
            field=models.PositiveIntegerField(
                help_text=(
                    "Auto progressive serial for"
                    " (lot, client_agency, contractor_company)"
                )
            ),
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.UniqueConstraint(
                fields=("lot", "client_agency", "contractor_company", "version"),
                name="unique_contract_version_per_lot_pair",
            ),
        ),
    ]
