# Generated by Django 5.2.6 on 2026-02-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchange_agreement", "0008_backfill_contract_end_date_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="short_description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional short label for compact displays",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="code",
            field=models.CharField(
                help_text="Route identifier (unique within the lot)", max_length=64
            ),
        ),
    ]
