# SPDX-FileCopyrightText: 2025-2026 AGENZIA TPL BACINO CITTA' METROPOLITANA MILANO, MONZA E BRIANZA, LODI, PAVIA
# SPDX-License-Identifier: EUPL-1.2
# Generated by Django 5.2.6 on 2026-02-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchange_agreement", "0009_lot_short_description_alter_route_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicatordef",
            name="sql_procedure_name",
            field=models.CharField(
                blank=True,
                help_text="Stable reference to the external SQL procedure/function.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="indicatordef",
            name="sql_snippet",
            field=models.TextField(
                blank=True,
                help_text=(
                    "Optional SQL documentation snippet"
                    " (not executed by this service)."
                ),
            ),
        ),
    ]
