# Generated by Django 5.2.6 on 2026-02-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchange_agreement", "0010_indicatordef_sql_procedure_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="structure",
            name="validation_schema",
        ),
        migrations.AddField(
            model_name="structure",
            name="definition",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text=(
                    "Structured mandatory-field definition used"
                    " by external processors. "
                    "Example: {'xpath': '//EstimatedVehicleJourney', 'fields': "
                    "['LineRef', 'DirectionRef']}.\n\n"
                    "Technical note: '//' in XPath means descendant-or-self"
                    " and matches nodes at any depth."
                ),
            ),
        ),
    ]
