# Generated by Django 5.2.6 on 2026-02-16 17:04

import django.db.models.deletion
import django.db.models.functions.datetime
import rpsd_config.exchange_agreement.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_agreement", "0011_remove_structure_validation_schema_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "role_to_assign",
                    models.CharField(
                        choices=[
                            ("contract_admin", "Contract admin"),
                            ("contract_reader", "Contract reader"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=rpsd_config.exchange_agreement.models._default_invitation_expiration
                    ),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_invitations_accepted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="exchange_agreement.contract",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_invitations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract invitation",
                "verbose_name_plural": "Contract invitations",
                "indexes": [
                    models.Index(
                        fields=["contract", "status"],
                        name="exchange_ag_contrac_d2c00f_idx",
                    ),
                    models.Index(fields=["email"], name="exchange_ag_email_34b2f6_idx"),
                    models.Index(fields=["token"], name="exchange_ag_token_ba84b5_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("contract", "email", "role_to_assign"),
                        name="unique_pending_contract_invitation_per_email_role",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ContractMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("contract_admin", "Contract admin"),
                            ("contract_reader", "Contract reader"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="exchange_agreement.contract",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_memberships_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract membership",
                "verbose_name_plural": "Contract memberships",
                "indexes": [
                    models.Index(
                        fields=["contract", "role"],
                        name="exchange_ag_contrac_4852fb_idx",
                    ),
                    models.Index(
                        fields=["user"], name="exchange_ag_user_id_d75eab_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("contract", "user"),
                        name="unique_contract_membership_user",
                    )
                ],
            },
        ),
    ]
