# Generated by Django 5.2.6 on 2026-02-16 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange_agreement", "0012_contractinvitation_contractmembership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contractinvitation",
            name="unique_pending_contract_invitation_per_email_role",
        ),
        migrations.AlterField(
            model_name="contractinvitation",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Optional target email. If empty, the invitation is open and can be used by the first user who accepts the token.",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="contractinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email__isnull", False), ("status", "pending")),
                fields=("contract", "email", "role_to_assign"),
                name="unique_pending_contract_invitation_per_email_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="contractinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email__isnull", True), ("status", "pending")),
                fields=("contract", "role_to_assign"),
                name="unique_pending_open_contract_invitation_per_role",
            ),
        ),
    ]
