# Generated by Django 5.2.6 on 2026-02-24 22:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "exchange_agreement",
            "0013_remove_contractinvitation_unique_pending_contract_invitation_per_email_role_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="route",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="stops",
        ),
        migrations.RemoveField(
            model_name="tripstop",
            name="stop",
        ),
        migrations.RemoveField(
            model_name="tripstop",
            name="trip",
        ),
        migrations.DeleteModel(
            name="Route",
        ),
        migrations.DeleteModel(
            name="Stop",
        ),
        migrations.DeleteModel(
            name="Trip",
        ),
        migrations.DeleteModel(
            name="TripStop",
        ),
    ]
