# SPDX-FileCopyrightText: 2025-2026 AGENZIA TPL BACINO CITTA' METROPOLITANA MILANO, MONZA E BRIANZA, LODI, PAVIA
# SPDX-License-Identifier: EUPL-1.2
# Generated by Django 5.2.6 on 2026-02-26 10:58

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchange_agreement", "0014_remove_trip_route_remove_trip_stops_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("schema_version", models.CharField(default="1.0", max_length=16)),
                ("options", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Flow profile",
                "verbose_name_plural": "Flow profiles",
                "ordering": ["code"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="exchange_ag_is_acti_701737_idx"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="contract",
            name="flow_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="Operational flow profile associated to this contract.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="exchange_agreement.flowprofile",
            ),
        ),
    ]
