# Generated by Django 5.2.6 on 2026-02-26 11:40

import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchange_agreement", "0015_flowprofile_contract_flow_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractPublication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("publication_version", models.PositiveIntegerField()),
                (
                    "published_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "snapshot_schema_version",
                    models.CharField(default="1.0", max_length=16),
                ),
                ("snapshot", models.JSONField(default=dict)),
                ("snapshot_checksum", models.CharField(blank=True, max_length=64)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to="exchange_agreement.contract",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_publications_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract publication",
                "verbose_name_plural": "Contract publications",
                "ordering": ["-published_at", "-publication_version"],
                "indexes": [
                    models.Index(
                        fields=["contract", "-published_at"],
                        name="exchange_ag_contrac_2a6529_idx",
                    ),
                    models.Index(
                        fields=["snapshot_checksum"],
                        name="exchange_ag_snapsho_86b327_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("contract", "publication_version"),
                        name="unique_contract_publication_version",
                    )
                ],
            },
        ),
    ]
