# SPDX-FileCopyrightText: 2026 AGENZIA TPL BACINO CITTA' METROPOLITANA MILANO, MONZA E BRIANZA, LODI, PAVIA
# SPDX-License-Identifier: EUPL-1.2
# Generated by Django 5.2.6 on 2026-05-08

import django.core.validators
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchange_agreement", "0027_agency_membership_sync_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "code",
                    models.CharField(
                        max_length=96,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message=(
                                    "Flow code must match "
                                    "^[a-z0-9][a-z0-9-]*_[0-9]{3}"
                                    "(?:[a-z0-9-]*)?$."
                                ),
                                regex=(
                                    "^[a-z0-9][a-z0-9-]*_[0-9]{3}"
                                    "(?:[a-z0-9-]*)?$"
                                ),
                            )
                        ],
                    ),
                ),
                (
                    "engine",
                    models.CharField(
                        choices=[("prefect", "Prefect")],
                        default="prefect",
                        max_length=32,
                    ),
                ),
                ("deployment_name", models.CharField(max_length=255)),
                (
                    "supported_what",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message=(
                                    "Supported what must use canonical filename "
                                    "stem syntax (example: netex or siri-pt)."
                                ),
                                regex="^[a-z0-9]+(?:-[a-z0-9]+)*$",
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("deprecated", "Deprecated"),
                            ("disabled", "Disabled"),
                        ],
                        default="active",
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("version", models.CharField(default="001", max_length=32)),
            ],
            options={
                "verbose_name": "Operational flow",
                "verbose_name_plural": "Operational flows",
                "ordering": ["supported_what", "code"],
                "indexes": [
                    models.Index(fields=["status"], name="exchange_ag_status_8c0478_idx"),
                    models.Index(
                        fields=["supported_what"],
                        name="exchange_ag_support_1da89f_idx",
                    ),
                ],
            },
        ),
    ]
