# Generated by Django 5.2.6 on 2025-10-12 23:28

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("exchange_agreement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LineAdminProxy",
            fields=[],
            options={
                "verbose_name": "Line",
                "verbose_name_plural": "Lines",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("exchange_agreement.line",),
        ),
        migrations.CreateModel(
            name="LotAdminProxy",
            fields=[],
            options={
                "verbose_name": "Lot",
                "verbose_name_plural": "Lots",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("exchange_agreement.lot",),
        ),
        migrations.CreateModel(
            name="StopAdminProxy",
            fields=[],
            options={
                "verbose_name": "Stop",
                "verbose_name_plural": "Stops",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("exchange_agreement.stop",),
        ),
        migrations.CreateModel(
            name="TripAdminProxy",
            fields=[],
            options={
                "verbose_name": "Trip",
                "verbose_name_plural": "Trips",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("exchange_agreement.trip",),
        ),
    ]
