# Generated by Django 5.2.6 on 2026-01-07 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_service_net", "0001_initial"),
        (
            "exchange_agreement",
            "0002_route_remove_line_authority_remove_line_lot_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="LineAdminProxy",
        ),
        migrations.CreateModel(
            name="RouteAdminProxy",
            fields=[],
            options={
                "verbose_name": "Route",
                "verbose_name_plural": "Routes",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("exchange_agreement.route",),
        ),
    ]
