# SPDX-FileCopyrightText: 2025-2026 AGENZIA TPL BACINO CITTA' METROPOLITANA MILANO, MONZA E BRIANZA, LODI, PAVIA
# SPDX-License-Identifier: EUPL-1.2
# Generated by Django 5.2.6 on 2025-10-12 23:28

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("exchange_agreement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractAdminProxy",
            fields=[],
            options={
                "verbose_name": "Contract",
                "verbose_name_plural": "Contracts",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("exchange_agreement.contract",),
        ),
        migrations.CreateModel(
            name="ContractDocumentAdminProxy",
            fields=[],
            options={
                "verbose_name": "Contract document",
                "verbose_name_plural": "Contract documents",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("exchange_agreement.contractdocument",),
        ),
        migrations.CreateModel(
            name="ContractIndicatorAdminProxy",
            fields=[],
            options={
                "verbose_name": "Contract indicator",
                "verbose_name_plural": "Contract indicators",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("exchange_agreement.contractindicator",),
        ),
    ]
