# Generated by Django 5.2.6 on 2026-02-16 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_agreements", "0001_initial"),
        ("exchange_agreement", "0012_contractinvitation_contractmembership"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractInvitationAdminProxy",
            fields=[],
            options={
                "verbose_name": "Contract invitation",
                "verbose_name_plural": "Contract invitations",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("exchange_agreement.contractinvitation",),
        ),
        migrations.CreateModel(
            name="ContractMembershipAdminProxy",
            fields=[],
            options={
                "verbose_name": "Contract membership",
                "verbose_name_plural": "Contract memberships",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("exchange_agreement.contractmembership",),
        ),
    ]
