# Generated by Django 5.2.6 on 2026-02-26 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_agreements", "0002_contractinvitationadminproxy_and_more"),
        ("exchange_agreement", "0015_flowprofile_contract_flow_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowProfileAdminProxy",
            fields=[],
            options={
                "verbose_name": "Flow profile",
                "verbose_name_plural": "Flow profiles",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("exchange_agreement.flowprofile",),
        ),
    ]
