# Generated by Django 5.2.6 on 2026-02-26 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_agreements", "0003_flowprofileadminproxy"),
        ("exchange_agreement", "0016_contractpublication"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractPublicationAdminProxy",
            fields=[],
            options={
                "verbose_name": "Contract publication",
                "verbose_name_plural": "Contract publications",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("exchange_agreement.contractpublication",),
        ),
    ]
