# SPDX-FileCopyrightText: 2026 AGENZIA TPL BACINO CITTA' METROPOLITANA MILANO, MONZA E BRIANZA, LODI, PAVIA
# SPDX-License-Identifier: EUPL-1.2
# Generated by Django 5.2.6 on 2026-05-08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_agreements", "0004_contractpublicationadminproxy"),
        ("exchange_agreement", "0028_operationalflow"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationalFlowAdminProxy",
            fields=[],
            options={
                "verbose_name": "Operational flow",
                "verbose_name_plural": "Operational flows",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("exchange_agreement.operationalflow",),
        ),
    ]
