services:
  postgis:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: rpsd
      POSTGRES_USER: rpsd
      POSTGRES_PASSWORD: rpsd
    volumes:
      - ../mnt/postgres-data:/var/lib/postgresql/data
      - ../scripts/postgis-init.sql:/docker-entrypoint-initdb.d/01-postgis.sql:ro
    networks:
      rpsd-dapr:
        aliases:
          - postgis

networks:
  rpsd-dapr:
    external: true
    name: rpsd-dapr
