############################
# Dapr platform
############################
include:
  - ./docker-compose-dapr.yml
  - ./docker-compose-database.yml
  - ./docker-compose-keycloak.yml

services:
  rpsd-config:
    extends:
      file: ./docker-compose-base.yml
      service: rpsd-config
    depends_on:
      - postgis
      - keycloak-db
      - keycloak
      
  ############################
  # Dapr sidecar
  ############################
  rpsd-config-dapr:
    extends:
      file: ./docker-compose-base.yml
      service: rpsd-config-dapr
    depends_on:
      - placement
      - scheduler
      - redis
    ports:
      - "12080:8000"
