"""
Django settings for rpsd_config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from decouple import AutoConfig

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent.parent
env = AutoConfig(search_path=str(PROJECT_ROOT))


def _csv_list(value: str) -> list[str]:
    return [item.strip() for item in value.split(",") if item.strip()]


def _env_str(name: str, *, default: str = "") -> str:
    value = env(name, default=default)
    return value if isinstance(value, str) else str(value)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-gc*7f_p9)xhm6itzdtb(cpkt_pjpl0e-pp7kjn0(u=6+n+i1lp"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", default=True, cast=bool)

_allowed_hosts = _env_str("DJANGO_ALLOWED_HOSTS", default="")
ALLOWED_HOSTS = _csv_list(_allowed_hosts)
CSRF_TRUSTED_ORIGINS = _csv_list(
    _env_str("DJANGO_CSRF_TRUSTED_ORIGINS", default="")
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.openid_connect",
    "leaflet",
    "django.contrib.gis",
    "rpsd_config.app1",
    #"rpsd_config.exchange_agreement",
    "rpsd_config.exchange_agreement.apps.ExchangeAgreementConfig",
    "rpsd_config.admin_stakeholders",
    "rpsd_config.admin_agreements",
    "rpsd_config.admin_dataset_exchange",
    "rpsd_config.admin_service_net",
]





LEAFLET_CONFIG = {
    "DEFAULT_CENTER": (45.4642637, 9.1896343),
    "DEFAULT_ZOOM": 13,
    "MIN_ZOOM": 2,
    "MAX_ZOOM": 19,   # <-- NON andare oltre 19 con OSM standard
    "SCALE": "metric",
    "RESET_VIEW": True,
    "TILES": [
        (
            "OSM",
            "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
            {
                "attribution": "&copy; OpenStreetMap contributors",
                "maxZoom": 19,          # zoom massimo consentito dalla mappa
                "maxNativeZoom": 19,    # i tile esistono nativamente fino a 19
                # "detectRetina": True, # opzionale
            },
        )
    ],
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "rpsd_config.server.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "rpsd_config.server.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": env("POSTGRES_DB", default="rpsd"),
        "USER": env("POSTGRES_USER", default="rpsd"),
        "PASSWORD": env("POSTGRES_PASSWORD", default="rpsd"),
        "HOST": env("POSTGRES_HOST", default="postgis"),
        "PORT": env("POSTGRES_PORT", default="5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Authentication / OIDC (Keycloak via django-allauth)
SITE_ID = env("SITE_ID", default=1, cast=int)

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

_oidc_provider_id = env("OIDC_PROVIDER_ID", default="keycloak")
_oidc_discovery_url = env(
    "KEYCLOAK_DISCOVERY_URL",
    default=(
        "http://keycloak:8080/realms/rapsodia/"
        ".well-known/openid-configuration"
    ),
)
_oidc_authorization_endpoint = _env_str(
    "OIDC_AUTHORIZATION_ENDPOINT_URL",
    default="",
)
_oidc_issuer = _env_str("OIDC_ISSUER_URL", default="")
_oidc_client_id = env("OIDC_CLIENT_ID", default="django")
_oidc_client_secret = env("OIDC_CLIENT_SECRET", default="django-secret")
_oidc_fetch_userinfo = env("OIDC_FETCH_USERINFO", default=False, cast=bool)

_oidc_apps = []
if _oidc_discovery_url and _oidc_client_id and _oidc_client_secret:
    _oidc_app_settings = {
        "server_url": _oidc_discovery_url,
        "fetch_userinfo": _oidc_fetch_userinfo,
    }
    if _oidc_authorization_endpoint:
        _oidc_app_settings["authorization_endpoint"] = (
            _oidc_authorization_endpoint
        )
    if _oidc_issuer:
        _oidc_app_settings["issuer"] = _oidc_issuer

    _oidc_apps = [
        {
            "provider_id": _oidc_provider_id,
            "name": "Keycloak",
            "client_id": _oidc_client_id,
            "secret": _oidc_client_secret,
            "settings": _oidc_app_settings,
        }
    ]

SOCIALACCOUNT_PROVIDERS = {
    "openid_connect": {
        "APPS": _oidc_apps,
    }
}
SOCIALACCOUNT_ADAPTER = "rpsd_config.server.socialaccount_adapter.RpsdSocialAccountAdapter"

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_SIGNUP_FIELDS = ["username*", "password1*", "password2*"]
